name: Build Xtream Player
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodları çek
        uses: actions/checkout@v3
      - name: Flutter Setup
        uses: subosito/flutter-action@v2
      - name: Ortam değişkenleri yükle
        run: flutter pub get
      - name: APK Build
        run: flutter build apk --release
      - name: Build tamamlandı
        run: echo "Yeni build başarıyla oluşturuldu!"
